name: Deploy to EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/ec2-user/Practice-

            echo "========== STARTING DEPLOYMENT =========="

            echo "Current Directory:"
            pwd

            echo "Pull latest code..."
            git pull origin main

            echo "Stopping old containers..."
            docker compose down

            echo "Building new containers..."
            docker compose up --build -d

            echo "Removing unused Docker images..."
            docker image prune -f

            echo "Running containers:"
            docker ps

            echo "========== DEPLOYMENT COMPLETE =========="